# Generated by Django 5.1.6 on 2025-03-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_remove_testimonial_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_l',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_m',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_s',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_xl',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_xxl',
            field=models.BooleanField(default=True),
        ),
    ]
