# Generated by Django 5.1.6 on 2025-03-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sizes',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sizes',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], default='M', max_length=10),
        ),
    ]
