# Generated by Django 5.1.6 on 2025-03-13 19:16

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_waitlistemailtemplate_waitlistuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistuser',
            name='tel1',
            field=phonenumber_field.modelfields.PhoneNumberField(default="+255758523353", max_length=128, region=None),
            preserve_default=False,
        ),
    ]
