# Generated by Django 5.1.6 on 2025-03-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_waitlistuser_tel1'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash')], default='card', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='stage',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ready', 'Ready'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
