# Generated by Django 5.1.6 on 2025-03-13 23:05

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuzzaz', '0002_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+255715250000', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
