# Generated by Django 5.1.6 on 2025-03-13 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuzzaz', '0003_customuser_tel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='tel',
            new_name='telephone',
        ),
    ]
