name: BeingThatGuy CI/CD Pipeline

# Trigger on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      #python3 -m pip install --upgrade pip
    #   - name: Install dependencies
    #     run: |
    #       python3 -m venv venv
    #       source venv/bin/activate
    #       pip install -r requirements.txt

      # Step 4: Deploy to server via SSH
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          key_path: /tmp/deploy_key
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/god.goals.glory
            git pull
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart BeingThatGuy
